services:
  qdrant-server:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  rag-api:
    build: .
    container_name: rag-api
    ports:
      - "8002:8000"
    environment:
      - QDRANT_HOST=qdrant-server
      - QDRANT_PORT=6333
      - COLLECTION_NAME=rag_biologia
    # volumes:                              # Opcional: si tienes config.yml para logs
    #   - ./config.yml:/app/config.yml
    volumes:
      - .:/app                     # Monta TODO el directorio actual dentro de /app
      - ./logs:/app/logs
      - ./config.yml:/app/config.yml
    depends_on:
      - qdrant-server
    restart: unless-stopped